name: Hello-World-Workflow

# Trigger the workflow on every push to the repository
#on: [push]
on: workflow_dispatch

jobs:
  # Job Name
  say-hello:
    # Use the latest Ubuntu runner provided by GitHub
    # Agent
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello, World!"