name: github-context-workflow

#on: [ push ]
on: workflow_dispatch

jobs:
  print-github-context:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Context
        run: |
          echo "GitHub Context: ${{ toJson(github) }}"

      - name: Display Branch Name
        run: echo "The current branch is ${{ github.ref_name }}"