name: secrets-workflow

#on: [ push ]
on: workflow_dispatch

env:
  # Define an environment variable for the workflow
  GREETING: "Hello from GitHub Actions!"
  PROJECT: "roboshop"
  COMPONENT: "catalogue"

jobs:
  print-github-context:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Context
        run: |
          echo "GitHub Context: ${{ toJson(github) }}"

      - name: Display Branch Name
        run: echo "The current branch is ${{ github.ref_name }}"

      - name: Use Environment Variables
        run: |
          echo "$GREETING"
          echo "Project: $PROJECT"
          echo "Component: $COMPONENT"

      - name: Print Secrets
        run: |
          echo "Using secrets in GitHub Actions"
          echo "Database Username: ${{ secrets.DB_USER }}"
          echo "Database Password: ${{ secrets.DB_PASSWORD }}"
          

      - name: Print Variables
        run: |
          echo "Using variables in GitHub Actions"
          echo "Database URL: ${{ vars.DB_URL }}"
