name: outputs-workflow

on: [ push ]

env:
  # Define an environment variable for the workflow
  GREETING: "Hello from GitHub Actions!"
  PROJECT: "roboshop"
  COMPONENT: "catalogue"

jobs:
  carry-output:
    runs-on: ubuntu-latest

    steps:

      # These Variables are visible only with in the JOB
      - name: Build Image
        id: build-image
        run: |
          echo "version=1.0.0" >> $GITHUB_OUTPUT
          echo "image-name=1.0.0" >> $GITHUB_OUTPUT

      - name: Use Output
        run: |
          echo "The version is : ${{ steps.build-image.outputs.version }}"
          echo "The image name is : ${{ steps.build-image.outputs.image-name }}"
          

      # These Variables are visible entire workflow
      - name: GitHub Env variables
        id: github-env
        run: |
          echo "COMPONENT=catalogue" >> $GITHUB_ENV
          echo "PROJECT=roboshop" >> $GITHUB_ENV
          echo "LANGUAGE=nodejs" >> $GITHUB_ENV

      - name: Print GitHub Env variables
        run: |
          echo "The Component is : $COMPONENT"
          echo "The Project is : $PROJECT"
          echo "The Language is : $LANGUAGE"
